spring:
  application:
    name: ojt_BE
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${DB_SOURCE}:3306/ojt_metadb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_ID}
    password: ${DB_PW}

  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/ojt_datadb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_ID}
    password: ${DB_PW}

clova:
  ocr:
    url: https://naveropenapi.apigw.ntruss.com/vision-ocr/v1/ocr
    client-id: YOUR_CLIENT_ID
    client-secret: YOUR_CLIENT_SECRET
